### ISSUE TITLE
Oversized STL file in Cura, can't scale down enough to print

### ISSUE THREAD

**Issue by arthurlutz** [VascoRibeiroPereira/phone-spectrophotometer#7]
Opening the STL files in Cura I get *huge* models, trying to put to 1% scale is still not enough to get them to a acceptable size to print. 

![Screenshot from 2019-09-07 09-41-41](https://user-images.githubusercontent.com/108437/64471618-1158c880-d154-11e9-806d-cc483b1a04a4.png)
![Screenshot from 2019-09-07 09-40-55](https://user-images.githubusercontent.com/108437/64471619-1158c880-d154-11e9-9718-20ce041e6c44.png)

Do you know what the problem could be ?

**Comment by VascoRibeiroPereira** [comment]
Hello,
Thank you for your feedback. It's probably because I made some mistake when exporting to stl. I've corrected the models and I've tested successfully in Cura. ;)
