### ISSUE TITLE
Add link to thingiverse

### ISSUE THREAD

**Issue by arthurlutz** [VascoRibeiroPereira/phone-spectrophotometer#8]
For some users it's easier to use thingiverse than github, maybe it would be nice to add a link to  https://www.thingiverse.com/thing:3185420 (and the other way round)

**Comment by VascoRibeiroPereira** [comment]
It's a nice idea indeed. I'll make the links and update the files in Thingiverse (they are still oversized). I've put the model there at the beginning of the project but drifted to GitHub by a reviewer suggestion (and its good to follow their suggestions until publishing :D)

**Comment by VascoRibeiroPereira** [comment]
Done! Thank you for your feedback.
