### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by XavCC** [VascoRibeiroPereira/phone-spectrophotometer#9]
**In order to find together a good way for a french translation of the content**
I open this issue to discuss some steps, some format, before cloning this repo and then pull request.

**File name format**
How to name files for french translated content?
+ Something like `README-fr.md` or `.../How-To/Booklet_Spectroscopy_Fr_Activity.pdf` for example
+ Another idea

**Keeping `.pdf` or moving to `.md` for files in `.pdf`**

+ An easy way to to make specs and explanation files editable/manageable could be take advantage of translation processes to provide the file in French in `.md`

**A specific branch for translation**

+ Should use a dedicated branch named `translation` to pull first draft translated contents, that allows iteration and review before adding clear new language resources in master branch ?

**Comment by VascoRibeiroPereira** [comment]
> **In order to find together a good way for a french translation of the content**
> I open this issue to discuss some steps, some format, before cloning this repo and then pull request.

> **File name format**
> How to name files for french translated content?
> 
> * Something like `README-fr.md` or `.../How-To/Booklet_Spectroscopy_Fr_Activity.pdf` for example

Keeping the original name and end it in `-fr.md` seems good for me and easier to read/understand.

> **Keeping `.pdf` or moving to `.md` for files in `.pdf`**

Let's move it to `.md` it is indeed a good idea.
I didn't at the time because I was unfamiliar with GitHub (sorry!).

> * An easy way to to make specs and explanation files editable/manageable could be take advantage of translation processes to provide the file in French in `.md`
> 
> **A specific branch for translation**
> 
> * Should use a dedicated branch named `translation` to pull first draft translated contents, that allows iteration and review before adding clear new language resources in master branch ?

Yes, this seems good to me!

So, for now, I'll start moving the `.pdf` to `.md` files.

**Comment by VascoRibeiroPereira** [comment]
I think I can close this issue now:
1. All the `.pdf` files are now as `.md`
2. Added XavCC as a collaborator and protected the master branch from merge without my consent.
____

I think that this way XavCC can work smoothly around the translation?
Share your thoughts

**Comment by XavCC** [comment]
Hi @VascoRibeiroPereira 

Thank you for aour answers.

I agree with your proposal.

I will start working on translation this week-end {>_o}

**Comment by VascoRibeiroPereira** [comment]
Thank you for your feedback, I'll close the issue now.

I may do a Portuguese translation also soon ; )
